// Reads the staged StarDict triple at dict/wordnet/{base.ifo,base.idx,base.dict.dz}
// and emits a TypeScript module at src/core/dict/data/baseDictData.ts that
// exports the three buffers as base64 strings plus a `loadBaseDictFromGenerated()`
// function returning a DictBytes. The generated module is consumed by index.js
// via createStardictLookup.
//
// The generated file is committed-to-gitignore (~16MB of base64) — it's
// regenerable from the source binaries and nothing else in the build needs
// to inspect it after the bundle step.

import {readFile, writeFile, mkdir, stat} from 'node:fs/promises';
import {join, dirname} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const DICT_DIR = join(PROJECT_ROOT, 'dict', 'wordnet');
const OUT_FILE = join(
  PROJECT_ROOT,
  'src',
  'core',
  'dict',
  'data',
  'baseDictData.ts',
);

const log = (...args) => console.log(...args);

const ensureFile = async (path) => {
  try {
    await stat(path);
  } catch {
    throw new Error(
      `Missing source file: ${path}. Run \`npm run fetch:dict\` first.`,
    );
  }
};

const formatMb = (bytes) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;

const main = async () => {
  const ifoPath = join(DICT_DIR, 'base.ifo');
  const idxPath = join(DICT_DIR, 'base.idx');
  const dictPath = join(DICT_DIR, 'base.dict.dz');
  await ensureFile(ifoPath);
  await ensureFile(idxPath);
  await ensureFile(dictPath);

  const [ifoBytes, idxBytes, dictBytes] = await Promise.all([
    readFile(ifoPath),
    readFile(idxPath),
    readFile(dictPath),
  ]);

  log(`source: .ifo  ${formatMb(ifoBytes.length)}`);
  log(`source: .idx  ${formatMb(idxBytes.length)}`);
  log(`source: .dict.dz ${formatMb(dictBytes.length)}`);

  // Pull the bookname out of the .ifo so the build log surfaces what
  // we're shipping (no behavioural change — just an audit trail).
  const ifoText = ifoBytes.toString('utf-8');
  const booknameMatch = ifoText.match(/^bookname=(.*)$/m);
  const wordcountMatch = ifoText.match(/^wordcount=(\d+)/m);
  log(`bookname: ${booknameMatch ? booknameMatch[1] : '(unknown)'}`);
  log(`wordcount: ${wordcountMatch ? wordcountMatch[1] : '(unknown)'}`);

  const ifoB64 = ifoBytes.toString('base64');
  const idxB64 = idxBytes.toString('base64');
  const dictB64 = dictBytes.toString('base64');

  const totalB64Bytes = ifoB64.length + idxB64.length + dictB64.length;
  log(`emitted base64 total: ${formatMb(totalB64Bytes)}`);

  const generated =
    "// AUTO-GENERATED by scripts/buildBaseDict.mjs. Do not edit directly.\n" +
    "// Regenerate by running `npm run build:dict` after staging the\n" +
    "// source StarDict files at dict/wordnet/.\n" +
    "//\n" +
    `// Source: ${booknameMatch ? booknameMatch[1] : 'WordNet'} (${wordcountMatch ? wordcountMatch[1] : '?'} entries)\n` +
    "//\n" +
    "// eslint-disable\n" +
    "/* eslint-disable */\n" +
    "/* prettier-ignore */\n" +
    "import type {DictBytes} from '../stardictLookup';\n" +
    "import {decodeBase64} from '../../../sdk/base64';\n" +
    "\n" +
    `const BASE_IFO_B64 = ${JSON.stringify(ifoB64)};\n` +
    `const BASE_IDX_B64 = ${JSON.stringify(idxB64)};\n` +
    `const BASE_DICT_B64 = ${JSON.stringify(dictB64)};\n` +
    "\n" +
    "let cached: DictBytes | null = null;\n" +
    "\n" +
    "export const loadBaseDictFromGenerated = (): DictBytes => {\n" +
    "  if (!cached) {\n" +
    "    cached = {\n" +
    "      ifo: decodeBase64(BASE_IFO_B64),\n" +
    "      idx: decodeBase64(BASE_IDX_B64),\n" +
    "      dict: decodeBase64(BASE_DICT_B64),\n" +
    "    };\n" +
    "  }\n" +
    "  return cached;\n" +
    "};\n";

  await mkdir(dirname(OUT_FILE), {recursive: true});
  await writeFile(OUT_FILE, generated, 'utf-8');
  log(`wrote: ${OUT_FILE}`);
};

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
